[package]
name = "hsum"
version = "0.0.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = {version="4", features=["derive"]}
sha2 = "0.10.8"
sha3 = "0.10.8"
digest = "0.10.7"